"""Added More Methods

Revision ID: 2d55d1cffb4d
Revises: a67aa3fd9ac5
Create Date: 2023-05-26 19:47:35.874842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d55d1cffb4d'
down_revision = 'a67aa3fd9ac5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
