"""Updated models and seed.py

Revision ID: 9e4c3b112127
Revises: 2d55d1cffb4d
Create Date: 2023-05-28 14:53:06.824289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4c3b112127'
down_revision = '2d55d1cffb4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
