"""Added Band and Concert Methods

Revision ID: a67aa3fd9ac5
Revises: e9d2fe925691
Create Date: 2023-05-26 19:33:18.987616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67aa3fd9ac5'
down_revision = 'e9d2fe925691'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
